services:
    netgen.enhanced_selection.field_type:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\FieldType\EnhancedSelection\Type
        parent: ezpublish.fieldType
        # Field type services in eZ Platform need to be public
        public: true
        tags:
            - { name: ezpublish.fieldType, alias: sckenhancedselection }

    netgen.enhanced_selection.field_type.external_storage:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\FieldType\EnhancedSelection\EnhancedSelectionStorage
        # External storage services in eZ Platform need to be public
        public: true
        arguments:
            - "@netgen.enhanced_selection.field_type.storage_gateway"
        tags:
            - { name: ezpublish.fieldType.externalStorageHandler, alias: sckenhancedselection }

    netgen.enhanced_selection.field_type.converter:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\EnhancedSelectionConverter
        public: false
        tags:
            - { name: ezpublish.storageEngine.legacy.converter, alias: sckenhancedselection, lazy: true, callback: "::create" }

    netgen.enhanced_selection.field_type.storage_gateway:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\FieldType\EnhancedSelection\EnhancedSelectionStorage\Gateway\DoctrineStorage
        public: false
        arguments:
            - "@ezpublish.api.storage_engine.legacy.connection"

    netgen.enhanced_selection.field_type.indexable:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\FieldType\EnhancedSelection\SearchField
        public: false
        tags:
            - { name: ezpublish.fieldType.indexable, alias: sckenhancedselection }

    netgen.enhanced_selection.field_type.form.fieldtype_handler:
        class: Netgen\Bundle\EnhancedSelectionBundle\Form\FieldTypeHandler\EnhancedSelection
        arguments:
            - '@ezpublish.config.resolver'
        public: false
        tags:
            - { name: netgen.ezforms.form.fieldtype_handler, alias: sckenhancedselection }

    netgen.enhanced_selection.field_type.form_mapper:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\FieldType\EnhancedSelection\FormMapper
        public: false
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: sckenhancedselection }
            - { name: ez.fieldFormMapper.value, fieldType: sckenhancedselection }

    netgen.enhanced_selection.field_type.form:
        class: Netgen\Bundle\EnhancedSelectionBundle\Form\Type\FieldType\EnhancedSelectionFieldType
        # public: false
        arguments:
            - "@ezpublish.api.service.field_type"
        tags:
            - { name: form.type }
