services:
    netgen.enhanced_selection.search.solr.criterion_visitor.enhanced_selection:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\Search\Solr\Query\CriterionVisitor\EnhancedSelection
        public: false
        arguments:
            - "@ezpublish.search.common.field_name_resolver"
            - "@ezpublish.search.common.field_value_mapper.aggregate"
        tags:
            - { name: ezpublish.search.solr.query.content.criterion_visitor }
            - { name: ezpublish.search.solr.query.location.criterion_visitor }
